project:
  type: website
  output-dir: _site

website:
  title: "Untitled"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    pdf-engine: xelatex
    documentclass: ctexart
    classoption: "fontset=mac"
    include-in-header:
          text: |
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            \fancyhead{}
            \renewcommand{\headrulewidth}{0pt}
