project:
  type: website
  output-dir: _site

website:
  title: "Untitled"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    toc: true
  pdf:
    pdf-engine: xelatex
    documentclass: ctexart
    classoption: "fontset=mac"
    include-in-header:
          text: |
            \usepackage{fancyhdr}
            \pagestyle{fancy}
            \fancyhead{}
            \renewcommand{\headrulewidth}{0pt}
    docx:
      toc: true                          # 生成目录
      toc-depth: 3                       # 目录层级
      number-sections: true              # 章节编号
      highlight-style: github            # 代码高亮风格
      fig-width: 6                       # 图片宽度（英寸）
      fig-height: 4                      # 图片高度
